# Default values for payload.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: payload
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}


service: {}

resources: {}

autoscaling: {}

nodeSelector: {}

tolerations: []

affinity: {}
